### ISSUE TITLE
Plugin for id complete-manifest not found - localhost plugins

### ISSUE THREAD

**Issue by riccitensor** [lean-dojo/LeanDojoChatGPT#4]
The plugin gets installed properly

<img width="597" alt="Bildschirmfoto 2023-12-17 um 12 09 58" src="https://github.com/lean-dojo/LeanDojoChatGPT/assets/4107484/44fb72c8-9242-464a-976f-f7fdf9cd221f">

but then I can't make it work.

<img width="470" alt="Bildschirmfoto 2023-12-17 um 12 13 04" src="https://github.com/lean-dojo/LeanDojoChatGPT/assets/4107484/cd3b3cd8-91a8-4e11-93e1-4a8f87c53601">

**Comment by yangky11** [comment]
This seems to be a known issue and is awaiting OpenAI's fix: https://community.openai.com/t/local-plugin-failure-via-localhost-plugin-id-not-found/475197/30

**Comment by yangky11** [comment]
Related https://github.com/lean-dojo/LeanDojoChatGPT/issues/5
